spring:
  datasource:
    url: jdbc:mysql://drone-task.cbtqdbgj9bqg.us-east-1.rds.amazonaws.com:3306/drone
    username: admin
    password: 2zCRAge4GzzHlyCin6cG
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/drone
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

aws:
  key:
    id: AKIA3DQATDDUWIJPDYM6
    secret: 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
